config/routes.rb
Rails.application.routes.draw do

  resources :payments, only: [:new, :create] do
    delete '/cancel_subscription_plan' => "payments#cancel_subscription_plan"
  end

  resources :job_portals do
    collection do
      get '/vacancies' => "job_portals#vacancies"
    end
  end

  namespace :admin do
    resources :companies
    resources :job_portals
    resources :transactions
    put '/transactions/approve_transaction/:id' => "transactions#approve_transaction"
    put '/job_portals/approve_job/:id' => "job_portals#approve_job"
    resources :candidates do
      member do
        post 'upload_avatar'
        get 'get_avatar'
        delete 'delete_avatar'
      end
    end
    put '/candidates/approve_user/:id' => "candidates#approve_user"
    resources :sites
    resources :sectors
  end
  get '/dashboard' => "dashboard#index", as: :user_root

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  resources :sites
  resources :feeds

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => 'registrations'}
  get '/news_sites' => "news#news_sites", format: 'json'

  resources :news, except: [:destroy, :create, :new, :edit, :show, :update] do
    collection do
      get ':site_id/entries'  => 'news#news_entries'
      get '/first_site' => "news#first_site"
      get '/latest_news' => "news#latest_news"
      get '/news_filters' => "news#news_filters"
    end
  end
  resources :candidates, except: [:destroy, :edit, :show, :update] do
    member do
      get '/people_detail' => "candidates#people_detail"
    end
    collection do
      get '/people_filters' => "candidates#people_filters"
      get '/people_list' => "candidates#people_list"
    end
  end
  resources :organization, except: [:destroy, :create, :new, :edit, :show, :update] do
    member do
      get '/ma_transaction' => "organization#ma_transaction"
      get '/advisor_transaction' => "organization#advisor_transaction"
      get '/organization_detail' => "organization#organization_detail"
    end
    collection do
      get '/organization_filters' => "organization#organization_filters"
      get '/organization_list' => "organization#organization_list"
      get '/organization_sectors'  => "organization#organization_sectors"
    end
  end

  resources :transactions, except: [:destroy, :show] do
    collection do
      get '/transaction_filters' => "transactions#transaction_filters"
      get '/transaction_list' => "transactions#transaction_list"
      get '/recent_deals' => "transactions#recent_deals"
    end
  end

  get '/pricing' => "static_pages#price"

  root "static_pages#index"
end

app/models/feed.rb
require 'nokogiri'
class Feed < ActiveRecord::Base
  belongs_to :site
  paginates_per 25



  private
  def self.add_news(news, site)
    if news && news.length != 0
      news.each do |latet_news|
        unless exists? :title => latet_news.title
          create!(
            title: latet_news.title.strip,
            url: latet_news.url,
            published: latet_news.published,
            entry_url: latet_news.entry_id,
            summary:  sanitize_content(latet_news.summary, site.name),
            site_id: site.id,
            category: latet_news.categories,
            image_url: latet_news.image,
            author: latet_news.author
            )
        end
      end
    end
  end

  def self.sanitize_content(content, site_name)
    summary = content
    if site_name == "Reuters"
      summary = ActionController::Base.helpers.strip_tags(summary)
    elsif site_name == "TechCrunch"
      entry = Nokogiri::HTML(summary)
      entry.search('//a[(starts-with(@href, "http://"))]').each do |a|
        a.replace("")
      end
      entry.search("body").each do |cont|
        summary = cont.to_html
      end
    end
    return summary
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:title, :url, :image_url, :entry_url, :author, :category, :summary, :published)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_area :image_url %>
  </div>
  <div class="field">
    <%= f.label :entry_url %><br>
    <%= f.text_area :entry_url %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_area :category %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.datetime_select :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Image url</th>
      <th>Entry url</th>
      <th>Author</th>
      <th>Category</th>
      <th>Summary</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.title %></td>
        <td><%= feed.url %></td>
        <td><%= feed.image_url %></td>
        <td><%= feed.entry_url %></td>
        <td><%= feed.author %></td>
        <td><%= feed.category %></td>
        <td><%= feed.summary %></td>
        <td><%= feed.published %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @feed.image_url %>
</p>

<p>
  <strong>Entry url:</strong>
  <%= @feed.entry_url %>
</p>

<p>
  <strong>Author:</strong>
  <%= @feed.author %>
</p>

<p>
  <strong>Category:</strong>
  <%= @feed.category %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @feed.summary %>
</p>

<p>
  <strong>Published:</strong>
  <%= @feed.published %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>