config/routes.rb
Rails.application.routes.draw do

  resources :payments, only: [:new, :create] do
    delete '/cancel_subscription_plan' => "payments#cancel_subscription_plan"
  end

  resources :job_portals do
    collection do
      get '/vacancies' => "job_portals#vacancies"
    end
  end

  namespace :admin do
    resources :companies
    resources :job_portals
    resources :transactions
    put '/transactions/approve_transaction/:id' => "transactions#approve_transaction"
    put '/job_portals/approve_job/:id' => "job_portals#approve_job"
    resources :candidates do
      member do
        post 'upload_avatar'
        get 'get_avatar'
        delete 'delete_avatar'
      end
    end
    put '/candidates/approve_user/:id' => "candidates#approve_user"
    resources :sites
    resources :sectors
  end
  get '/dashboard' => "dashboard#index", as: :user_root

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  resources :sites
  resources :feeds

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => 'registrations'}
  get '/news_sites' => "news#news_sites", format: 'json'

  resources :news, except: [:destroy, :create, :new, :edit, :show, :update] do
    collection do
      get ':site_id/entries'  => 'news#news_entries'
      get '/first_site' => "news#first_site"
      get '/latest_news' => "news#latest_news"
      get '/news_filters' => "news#news_filters"
    end
  end
  resources :candidates, except: [:destroy, :edit, :show, :update] do
    member do
      get '/people_detail' => "candidates#people_detail"
    end
    collection do
      get '/people_filters' => "candidates#people_filters"
      get '/people_list' => "candidates#people_list"
    end
  end
  resources :organization, except: [:destroy, :create, :new, :edit, :show, :update] do
    member do
      get '/ma_transaction' => "organization#ma_transaction"
      get '/advisor_transaction' => "organization#advisor_transaction"
      get '/organization_detail' => "organization#organization_detail"
    end
    collection do
      get '/organization_filters' => "organization#organization_filters"
      get '/organization_list' => "organization#organization_list"
      get '/organization_sectors'  => "organization#organization_sectors"
    end
  end

  resources :transactions, except: [:destroy, :show] do
    collection do
      get '/transaction_filters' => "transactions#transaction_filters"
      get '/transaction_list' => "transactions#transaction_list"
      get '/recent_deals' => "transactions#recent_deals"
    end
  end

  get '/pricing' => "static_pages#price"

  root "static_pages#index"
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  has_many :company_sectors
  has_many :companies, through: :company_sectors
  has_many :sites
end

app/controllers/admin/sectors_controller.rb
class Admin::SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  def index
    @sectors = Sector.order('updated_at DESC').page(params[:page]).per(10)
  end

  def show
  end

  def new
    @sector = Sector.new
  end

  def edit
  end


  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to admin_sectors_url, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to admin_sectors_url, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to admin_sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_sector
      @sector = Sector.find(params[:id])
    end

    def sector_params
      params.require(:sector).permit(:name)
    end
end

app/views/admin/sectors/_form.html.erb
<div class="col-md-12">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :name, class: "control-label col-sm-4" do %>
        Name <i class="fa fa-star"></i>
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-6 col-sm-5">
    <%= f.submit 'Save', class: "btn btn-success" %>
    <%= link_to 'Back', admin_sectors_path, class: "btn btn-default" %>
  </div>
</div>

app/views/admin/sectors/edit.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading">Edit Sector
        </div>
        <div class="panel-body">
          <%= form_for @sector, url: {action: "update"}, html:{ class: "form-horizontal" } do |f| %>
          <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/sectors/index.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading" style="height: 48px">Sector List
          <p class="pull-right"><%= link_to 'Add Sector', new_admin_sector_path, class: "btn btn-primary btn-sm" %></p></div>
          <div class="panel-body">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @sectors.each do |sector| %>
                <tr>
                  <td><%= sector.name %></td>
                  <td><%= link_to '', '/admin/sectors/' + sector.id.to_s, class: "btn btn-xs btn-info fa fa-eye", title: "View" %>
                    <%= link_to '', edit_admin_sector_path(sector), class: "btn btn-xs btn-warning fa fa-edit", title: "Edit" %>
                    <%= link_to '', '/admin/sectors/' + sector.id.to_s, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger fa fa-trash-o", title: "Delete" %>
                  </td>
                </tr>
                <% end %>
                <% if @sectors.length == 0 %>
                <tr><td>No Record Found.</td></tr>
                <% end %>
              </tbody>
            </table>
            <div class="pull-right"><%= paginate @sectors %></div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/admin/sectors/new.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading">New Sector
        </div>
        <div class="panel-body">
          <%= form_for @sector, url: {action: "create"}, html:{ class: "form-horizontal" } do |f| %>
          <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/sectors/show.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading">Sector Information
        </div>
        <div class="panel-body">
          <form class="form-horizontal" role="form">
            <div class="col-md-12">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="control-label col-sm-4">Name:</label>
                  <div class="col-sm-8 form-control-static">
                    <%= @sector.name %>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-4 col-sm-5">
                <%= link_to 'Edit', edit_admin_sector_path(@sector), class: "btn btn-warning" %>
                <%= link_to 'Back', admin_sectors_path, class: "btn btn-default" %>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>