config/routes.rb
Rails.application.routes.draw do

  resources :payments, only: [:new, :create] do
    delete '/cancel_subscription_plan' => "payments#cancel_subscription_plan"
  end

  resources :job_portals do
    collection do
      get '/vacancies' => "job_portals#vacancies"
    end
  end

  namespace :admin do
    resources :companies
    resources :job_portals
    resources :transactions
    put '/transactions/approve_transaction/:id' => "transactions#approve_transaction"
    put '/job_portals/approve_job/:id' => "job_portals#approve_job"
    resources :candidates do
      member do
        post 'upload_avatar'
        get 'get_avatar'
        delete 'delete_avatar'
      end
    end
    put '/candidates/approve_user/:id' => "candidates#approve_user"
    resources :sites
    resources :sectors
  end
  get '/dashboard' => "dashboard#index", as: :user_root

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  resources :sites
  resources :feeds

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => 'registrations'}
  get '/news_sites' => "news#news_sites", format: 'json'

  resources :news, except: [:destroy, :create, :new, :edit, :show, :update] do
    collection do
      get ':site_id/entries'  => 'news#news_entries'
      get '/first_site' => "news#first_site"
      get '/latest_news' => "news#latest_news"
      get '/news_filters' => "news#news_filters"
    end
  end
  resources :candidates, except: [:destroy, :edit, :show, :update] do
    member do
      get '/people_detail' => "candidates#people_detail"
    end
    collection do
      get '/people_filters' => "candidates#people_filters"
      get '/people_list' => "candidates#people_list"
    end
  end
  resources :organization, except: [:destroy, :create, :new, :edit, :show, :update] do
    member do
      get '/ma_transaction' => "organization#ma_transaction"
      get '/advisor_transaction' => "organization#advisor_transaction"
      get '/organization_detail' => "organization#organization_detail"
    end
    collection do
      get '/organization_filters' => "organization#organization_filters"
      get '/organization_list' => "organization#organization_list"
      get '/organization_sectors'  => "organization#organization_sectors"
    end
  end

  resources :transactions, except: [:destroy, :show] do
    collection do
      get '/transaction_filters' => "transactions#transaction_filters"
      get '/transaction_list' => "transactions#transaction_list"
      get '/recent_deals' => "transactions#recent_deals"
    end
  end

  get '/pricing' => "static_pages#price"

  root "static_pages#index"
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  attr_accessor :editable
  belongs_to :company
  belongs_to :user

  # validates :email, uniqueness: true

  delegate :name, to: :company, allow_nil: true, prefix: :company

  scope :searchCandidate, -> (candidate_id, company_id, sector_id, title, city) {
    search_str = ""
    if city.kind_of?(Array) && city.include?(nil)
      search_str = "LOWER(city) IS NULL or  LOWER(city) IN (?)"
    else
      search_str = "LOWER(city) IN (?)"
    end
    joins(:company => [:sectors, :company_sectors]).
    where("candidates.id in (?) and LOWER(designation) like '%#{title.downcase}%' and sectors.id in (?) and candidates.company_id in (?)", candidate_id, sector_id, company_id).where(search_str, city).
    order(:name)
    }

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "150x150>" }, :default_url => ActionController::Base.helpers.asset_path('assets/people/missing_:style.jpg')

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def avatar_medium_url
    ApplicationController.helpers.asset_url(avatar.url(:medium))
  end

  def avatar_thumb_url
    ApplicationController.helpers.asset_url(avatar.url(:thumb))
  end

  def is_editable?(current_user)
    editable = false
    editable = true if self.email.downcase == current_user.email.downcase
    self.editable = editable
  end

  def full_address
    [street, city, state, country, pin_code].reject(&:blank?).join(', ')
  end

end

app/controllers/admin/candidates_controller.rb
class Admin::CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]
  layout false, only: [:approve_user, :upload_avatar, :get_avatar, :delete_avatar]
  layout 'admin'

  def index
    @candidates = Candidate.includes(:user, :company => (:sectors)).order('updated_at DESC').page(params[:page]).per(10)
  end

  def show
  end

  def new
    @candidate = Candidate.new
  end

  def edit
  end


  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to admin_candidates_url, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        flash[:notice] = "Email already exists"
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to admin_candidates_url, notice: 'Candidate was successfully updated.' }
        candidate = candidate_json(@candidate)
        format.json { render_json(true, candidate , 200)}
      else
        format.html { render :edit }
        format.json { render_json(false, @candidate.errors , :unprocessable_entity)}
      end
    end
  end

  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to admin_candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_avatar
    candidate = Candidate.find(params[:id])
    respond_with candidate do |format|
      format.json { render json: candidate.to_json(:methods => [:avatar_medium_url, :avatar_thumb_url]) }
    end
  end

  def delete_avatar
    candidate = Candidate.find(params[:id])
    candidate.avatar = nil
    candidate.save
    render_json(true, candidate.to_json(:methods => [:avatar_medium_url, :avatar_thumb_url]) , 200)
  end

  def approve_user
    if params[:id].present?
      user = User.find(params[:id])
      user.is_accept = params[:value]
      user.save
      if user.is_accept == true
        CandidateMailer.send_notification_to_user(user).deliver
      end
      head :ok
    end
  end

  def upload_avatar
    candidate = Candidate.update(params[:id], candidate_params)
    if candidate
      error_message =  candidate.errors.full_messages
      if error_message && !error_message.blank?
        render_json(false, {message: "candidate avatar upload failed try again! \n " + error_message.join(", ") } , 500)
      else
        render_json(true, candidate.to_json(:methods => [:avatar_medium_url, :avatar_thumb_url]), 200)
      end
    else
      render_json(false, {message: "candidate avatar upload failed."} , 500)
    end
  end

  def candidate_json(candidate)
    {
      id: candidate.id,
      name: candidate.name,
      email: candidate.email,
      company_name: candidate.company_name,
      sector_name: candidate.company.sectors.pluck(:name).join(","),
      joined: candidate.joined,
      designation: candidate.designation,
      bio: candidate.bio,
      work_history: candidate.work_history,
      industry_specialty: candidate.industry_specialty,
      board_member: candidate.board_member,
      education: candidate.education,
      phone: candidate.phone,
      skills: candidate.skills,
      language: candidate.language,
      location: candidate.full_address,
      editable: candidate.is_editable?(current_user),
      avatar: candidate.avatar.url(:medium)
    }
  end

  private

    def set_candidate
      @candidate = Candidate.find(params[:id])
      @candidate.is_editable?(current_user)
    end

    def candidate_params
      params.require(:candidate).permit(:id, :name, :email, :city, :language, :year, :company_id, :designation, :joined, :bio, :work_history, :industry_specialty, :board_member, :education, :phone, :avatar, :street, :state, :country, :pin_code, :skills)
    end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  layout :false, only: [:people_filters, :people_list, :people_detail]
  before_filter :trial_expired?, except: [:new, :create]
  before_action :authenticate_user!, except: [:new, :create]

  def new
    @candidate = Candidate.new
    @user = User.find_by(temp_token: params[:temp_token]) if params[:temp_token]
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if params[:candidate][:company_id].present?
      candidate_create_method(@candidate)
    else
      if params[:sector].present? && params[:company_name].present? && params[:company_type].present? && params[:website].present? && params[:city].present? && params[:country].present? && params[:landline]
        company = Company.find_or_create_by(name: params[:company_name], company_type_id: params[:company_type], website: params[:website])
        location = company.locations.create(city: params[:city], country: params[:country]) if company
        phone = company.phones.create(landline: params[:landline]) if company
        company_sector = CompanySector.create(company_id: company.id, sector_id: params[:sector]) if company
        @candidate[:company_id] = company.id if company
      end
      candidate_create_method(@candidate)
    end
  end

  def candidate_create_method(candidate)
    respond_to do |format|
      if candidate[:company_id].present? && candidate.save
        if candidate.user
          candidate.user.temp_token = nil if candidate.user
          candidate.user.save
        end

        CandidateMailer.candidate_notification_email(candidate, request.base_url).deliver
        format.html { redirect_to "/users/sign_in", notice: 'Candidate was successfully created. You will be receiving approval mail from admin for accessing your account.' }
        format.json { render :show, status: :created, location: candidate }
      else
        flash[:warning] = "Company information is required."
        format.html { render :new }
        format.json { render json: candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
  end

  def people_filters
    @success = true
    @candidates = Candidate.order("name")
    @sectors = Sector.order("name")
    @companies = Company.order("name")
    cities = Candidate.pluck("LOWER(city)").uniq.compact
    @cities = cities.map{ |i| i.titleize if i.present? }
  end

  def people_list
    candidate_id = params["candidate_id"]
    company_id = params["company_id"]
    sector_id = params["sector_id"]
    title = params["title"]
    city = params["city"].downcase  if params["city"].present?
    candidate_id = Candidate.pluck(:id) if candidate_id.blank?
    company_id = Company.pluck(:id) if company_id.blank?
    sector_id = Sector.pluck(:id) if sector_id.blank?
    city = Candidate.pluck("LOWER(city)").uniq if city.blank?
    @people = Candidate.searchCandidate(candidate_id, company_id, sector_id, title, city)
    @success = @people ? true : false
  end

  def people_detail
    member_id = params["id"]
    @person = Candidate.find(member_id)
    @person.is_editable?(current_user)
    @success = @person ? true : false
  end

  def candidate_params
    params.require(:candidate).permit(:id, :name, :email, :city, :language, :year, :company_id, :designation, :joined, :bio, :work_history, :industry_specialty, :board_member, :education, :phone, :avatar, :street, :state, :country, :pin_code, :skills, :user_id)
  end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/admin/candidates/_form.html.erb
<%= javascript_include_tag "admin-candidates" %>
<div class="col-md-12">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :name, class: "control-label col-sm-4" do %>
      Name <i class="fa fa-star"></i>
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "control-label col-sm-4" do %>
      Email
      <% end %>
      <div class="col-sm-8">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :street, class: "control-label col-sm-4" do %>
      Street
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :street, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :city, class: "control-label col-sm-4" do %>
      City <i class="fa fa-star"></i>
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :city, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :state, class: "control-label col-sm-4" do %>
      State
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :state, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :country, class: "control-label col-sm-4" do %>
      Country
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :country, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :language, class: "control-label col-sm-4" do %>
      Language
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :language, class: "form-control", 'data-role' => "tagsinput" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :company_id, class: "control-label col-sm-4" do %>
      Company <i class="fa fa-star"></i>
      <% end %>
      <div class="col-sm-8">
        <%= f.select(:company_id, Company.all.collect {|u| [u.name, u.id]}, { :prompt => 'Please Select'} , { class: "form-control" }) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :designation, class: "control-label col-sm-4" %>
      <div class="col-sm-8">
        <%= f.text_field :designation, class: "form-control" %>
      </div>
    </div>
    </div>
    <div class="col-md-6">
    <div class="form-group">
      <%= f.label 'Profile', class: "control-label col-sm-4" %>
      <div class="col-sm-8">
        <%= f.text_area :bio, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Skills', class: "control-label col-sm-4" %>
      <div class="col-sm-8">
        <%= f.text_field :skills, class: "form-control", 'data-role' => "tagsinput" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :work_history, class: "control-label col-sm-4" %>
      <div class="col-sm-8">
        <%= f.text_field :work_history, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Industry Speciality', class: "control-label col-sm-4" %>
      <div class="col-sm-8">
        <%= f.text_field :industry_specialty, class: "form-control" %>
      </div>
    </div>
     <div class="form-group">
      <%= f.label :board_member, class: "control-label col-sm-4" %>
      <div class="col-sm-8">
        <%= f.text_field :board_member, class: "form-control" %>
      </div>
    </div>
     <div class="form-group">
      <%= f.label :education, class: "control-label col-sm-4" %>
      <div class="col-sm-8">
        <%= f.text_field :education, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :phone, class: "control-label col-sm-4" do %>
      Phone
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :phone, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :joined, class: "control-label col-sm-4" %>
      <div class="col-sm-8">
        <%= f.text_field :joined, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :pin_code, class: "control-label col-sm-4" do %>
      Pin code
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :pin_code, class: "form-control" %>
      </div>
    </div>
    </div>
  </div>

<div class="form-group">
  <div class="col-sm-offset-4 col-sm-5">
    <%= f.submit 'Save', class: "btn btn-success" %>
    <%= link_to 'Back', admin_candidates_path, class: "btn btn-default" %>
  </div>
</div>

app/views/admin/candidates/edit.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading">Edit Candidate
        </div>
        <div class="panel-body">
          <%= form_for @candidate, url: {action: "update"}, html:{ class: "admin-candidate form-horizontal" } do |f| %>
          <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/candidates/index.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading" style="height: 48px">Candidate List
          <p class="pull-right"><%= link_to 'Add Candidate', new_admin_candidate_path, class: "btn btn-primary btn-sm" %></p></div>
          <div class="panel-body">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Company</th>
                  <th>Designation</th>
                  <th>Sector</th>
                  <th>Valid user</th>
                  <th class="action-width">Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @candidates.each do |candidate| %>
                <tr>
                  <td><%= candidate.name %></td>
                  <td><%= candidate.email %></td>
                  <td><%= candidate.phone %></td>
                  <td><%= candidate.company.name if candidate.company.present? %></td>
                  <td><%= candidate.designation %></td>
                  <td><%= candidate.company.sectors.first.name if candidate.company.present? %></td>
                  <% if candidate.user && candidate.user.is_accept? %>
                    <td><input class="user_is_accept" name="user[is_accept]" type="checkbox" checked disabled /></td>
                  <% else %>
                    <td><input class="user_is_accept" name="user[is_accept]" type="checkbox" data-userid="<%= candidate.user.id if candidate.user %>" /></td>
                  <% end %>
                  <td><%= link_to '', '/admin/candidates/' + candidate.id.to_s, class: "btn btn-xs btn-info fa fa-eye", title: "View" %>
                    <%= link_to '', edit_admin_candidate_path(candidate), class: "btn btn-xs btn-warning fa fa-edit", title: "Edit" %>
                    <%= link_to '', '/admin/candidates/' + candidate.id.to_s, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger fa fa-trash-o", title: "Delete" %>
                  </td>
                </tr>
                <% end %>
                <% if @candidates.length == 0 %>
                <tr><td>No Record Found.</td></tr>
                <% end %>
              </tbody>
            </table>
            <div class="pull-right"><%= paginate @candidates %></div>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
  $(".user_is_accept").change(function() {
    var result = false;
    if(this.checked){
      result = true;
      toastr.success("Candidate added successfully");
    }
    var request = $.ajax({
      url: "/admin/candidates/approve_user/" + $(this).data("userid"),
      type: "PUT",
      data: { value : result }
    });
    request.done(function(msg) {
      $("#log").html( msg );
    });
  });
</script>

app/views/admin/candidates/new.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading">New Candidate
        </div>
        <div class="panel-body">
          <%= form_for @candidate, url: {action: "create"}, html:{ class: "admin-candidate form-horizontal" } do |f| %>
          <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/candidates/show.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading">Candidate Information
        </div>
        <div class="panel-body">
          <form class="form-horizontal" role="form">
          <div class="col-md-12">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label col-sm-4">Name:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.name %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Email:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.email %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Street:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.street %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">City:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.city %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">State:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.state %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Country:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.country %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Language:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.language %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Company:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.company.name %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-4">Designation:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.designation %>
              </div>
            </div>
            </div>
            <div class="col-md-6">
            <div class="form-group">
              <label class="control-label col-sm-4">Skills:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.skills %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Profile:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.bio %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Work History:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.work_history %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Industry Speciality:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.industry_specialty %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Board Member</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.board_member %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-4">Education:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.education %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Phone:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.phone %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Joined Year:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.joined %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Pin Code:</label>
              <div class="col-sm-8 form-control-static">
                <%= @candidate.pin_code %>
              </div>
            </div>
            </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-4 col-sm-5">
                <%= link_to 'Edit', edit_admin_candidate_path(@candidate), class: "btn btn-warning" %>
                <%= link_to 'Back', admin_candidates_path, class: "btn btn-default" %>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>