config/routes.rb
Rails.application.routes.draw do

  resources :payments, only: [:new, :create] do
    delete '/cancel_subscription_plan' => "payments#cancel_subscription_plan"
  end

  resources :job_portals do
    collection do
      get '/vacancies' => "job_portals#vacancies"
    end
  end

  namespace :admin do
    resources :companies
    resources :job_portals
    resources :transactions
    put '/transactions/approve_transaction/:id' => "transactions#approve_transaction"
    put '/job_portals/approve_job/:id' => "job_portals#approve_job"
    resources :candidates do
      member do
        post 'upload_avatar'
        get 'get_avatar'
        delete 'delete_avatar'
      end
    end
    put '/candidates/approve_user/:id' => "candidates#approve_user"
    resources :sites
    resources :sectors
  end
  get '/dashboard' => "dashboard#index", as: :user_root

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  resources :sites
  resources :feeds

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => 'registrations'}
  get '/news_sites' => "news#news_sites", format: 'json'

  resources :news, except: [:destroy, :create, :new, :edit, :show, :update] do
    collection do
      get ':site_id/entries'  => 'news#news_entries'
      get '/first_site' => "news#first_site"
      get '/latest_news' => "news#latest_news"
      get '/news_filters' => "news#news_filters"
    end
  end
  resources :candidates, except: [:destroy, :edit, :show, :update] do
    member do
      get '/people_detail' => "candidates#people_detail"
    end
    collection do
      get '/people_filters' => "candidates#people_filters"
      get '/people_list' => "candidates#people_list"
    end
  end
  resources :organization, except: [:destroy, :create, :new, :edit, :show, :update] do
    member do
      get '/ma_transaction' => "organization#ma_transaction"
      get '/advisor_transaction' => "organization#advisor_transaction"
      get '/organization_detail' => "organization#organization_detail"
    end
    collection do
      get '/organization_filters' => "organization#organization_filters"
      get '/organization_list' => "organization#organization_list"
      get '/organization_sectors'  => "organization#organization_sectors"
    end
  end

  resources :transactions, except: [:destroy, :show] do
    collection do
      get '/transaction_filters' => "transactions#transaction_filters"
      get '/transaction_list' => "transactions#transaction_list"
      get '/recent_deals' => "transactions#recent_deals"
    end
  end

  get '/pricing' => "static_pages#price"

  root "static_pages#index"
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :company_type
  has_many :company_sectors, dependent: :destroy
  has_many :sectors, through: :company_sectors
  has_many :locations, dependent: :destroy
  has_many :phones, dependent: :destroy
  has_many :ma_transactions
  has_many :candidates
  has_many :job_portals

  validates :name, uniqueness: { case_sensitive: false }

  accepts_nested_attributes_for :locations, :phones, :company_sectors, :allow_destroy => true

  # validates :email, uniqueness: true

  scope :searchOrganization, -> (company_id, sector_id, city, country, hiring, fundraising) {
    search_str = ""
    search_str = " and LOWER(locations.city)='#{city.downcase}'" if city.present?
    search_str += " and LOWER(locations.country)='#{country.downcase}'" if country.present?
    search_str += " and companies.hiring = true" if hiring == "true"
    search_str += " and companies.fund_raising = true" if fundraising == "true"
    joins(:company_type, :sectors, :company_sectors, :locations, :phones).
    select("companies.id as company_id, companies.name, companies.website, companies.revenue, sectors.name as sector_name, locations.id as location_id, array_agg(phones.landline) as landline").
    where("companies.id in (?) and sectors.id in (?) #{search_str}", company_id,  sector_id).
    order("companies.name").group("companies.id, sectors.name, locations.id")
    }


end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  has_many :companies
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /admin/companies
  # GET /admin/companies.json
  def index
    @companies = Company.includes(:company_type).order('updated_at DESC').page(params[:page]).per(10)
  end

  # GET /admin/companies/1
  # GET /admin/companies/1.json
  def show
  end

  # GET /admin/companies/new
  def new
    @company = Company.new
    @company.locations.build
    @company.phones.build
    @company.company_sectors.build
  end

  # GET /admin/companies/1/established_date
  def edit
  end

  # POST /admin/companies
  # POST /admin/companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      begin
        @company.save!
      rescue ActiveRecord::RecordInvalid => e
        if e.message == 'Validation failed: Email has already been taken'
          flash[:notice] = "Email has already been taken"
          format.html { render :action => 'new' }
        else
          format.html { render :action => 'new' }
        end
      end
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully created.' }
    end
  end

  # PATCH/PUT /admin/companies/1
  # PATCH/PUT /admin/companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to admin_companies_url, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/companies/1
  # DELETE /admin/companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :employees_count, :established_date, :summary, :website, :revenue, :email, :hiring, :fund_raising, :company_type_id, locations_attributes: company_location_attrs, phones_attributes: company_phone_attrs, company_sectors_attributes: [:id, :sector_id, :_destroy])
    end

    def company_location_attrs
      [:id, :street, :state, :country, :city, :pin_code, :is_headquarter, :_destroy]
    end

    def company_phone_attrs
      [:id, :mobile, :fax, :landline, :_destroy]
    end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/views/admin/companies/_company_location.html.erb
<%= f.fields_for :locations do |location| %>
<div class="form-group">
  <%= location.label :street, class: "control-label col-sm-4" %>
  <div class="col-sm-8">
    <%= location.text_field :street, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= location.label :city, class: "control-label col-sm-4" do %>
   City <i class="fa fa-star"></i>
  <% end %>
  <div class="col-sm-8">
    <%= location.text_field :city, class: "form-control" %>
  </div>
</div>
</div>
<div class="col-md-6">
<div class="form-group">
  <%= f.label :website, class: "control-label col-sm-4" do %>
    Website <i class="fa fa-star"></i>
  <% end %>
  <div class="col-sm-8">
    <%= f.text_field :website, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :summary, class: "control-label col-sm-4" %>
  <div class="col-sm-8">
    <%= f.text_area :summary, class: "form-control" %>
  </div>
</div>
  <div class="form-group">
    <%= location.label :state, class: "control-label col-sm-4" %>
    <div class="col-sm-8">
      <%= location.text_field :state, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= location.label :country, class: "control-label col-sm-4" do %>
      Country <i class="fa fa-star"></i>
    <% end %>
    <div class="col-sm-8">
      <%= location.text_field :country, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= location.label :pin_code, class: "control-label col-sm-4" do %>
      Pin code
    <% end %>
    <div class="col-sm-8">
      <%= location.text_field :pin_code, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= location.label :is_headquarter, class: "control-label col-sm-4" %>
    <div class="col-sm-8">
      <%= location.check_box :is_headquarter %>
    </div>
  </div>
  <% end %>

app/views/admin/companies/_company_phone.html.erb
<%= f.fields_for :phones do |phone| %>
<div class="form-group">
  <%= phone.label :mobile, class: "control-label col-sm-4" do %>
    Mobile
  <% end %>
  <div class="col-sm-8">
    <%= phone.text_field :mobile, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= phone.label :landline, class: "control-label col-sm-4" do %>
    Land Line Number
  <% end %>
  <div class="col-sm-8">
    <%= phone.text_field :landline, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= phone.label :fax, class: "control-label col-sm-4" do %>
    FAX
  <% end %>
  <div class="col-sm-8">
    <%= phone.text_field :fax, class: "form-control" %>
  </div>
</div>
<% end %>

app/views/admin/companies/_form.html.erb
<%= javascript_include_tag "admin-companies" %>
<div class="col-md-12">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :name, class: "control-label col-sm-4" do %>
        Name <i class="fa fa-star"></i>
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <%= f.fields_for :company_sectors do |sector| %>
    <div class="form-group">
      <%= sector.label :sector_id, class: "control-label col-sm-4" do %>
        Sector <i class="fa fa-star"></i>
      <% end %>
      <div class="col-sm-8">
        <%= sector.select(:sector_id, Sector.all.collect {|u| [u.name, u.id]}, { :prompt => 'Please Select'} , { class: "form-control" }) %>
      </div>
    </div>
    <% end %>
    <div class="form-group">
      <%= f.label :employees_count, class: "control-label col-sm-4" do %>
      Employees Count
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :employees_count, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :established_date, class: "control-label col-sm-4" do %>
        Established Date
      <% end %>
      <div class="col-sm-8">
        <%= f.date_field :established_date, class: "form-control", max: Date.today.to_s %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "control-label col-sm-4" do %>
       Email <i class="fa fa-star"></i>
      <% end %>
      <div class="col-sm-8">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :revenue, class: "control-label col-sm-4" do %>
        Revenue
      <% end %>
      <div class="col-sm-8">
        <%= f.text_field :revenue, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :company_type_id, class: "control-label col-sm-4" do %>
       Company Type <i class="fa fa-star"></i>
      <% end %>
      <div class="col-sm-8">
        <%= f.select(:company_type_id, CompanyType.all.collect {|u| [u.name, u.id]}, { :prompt => 'Please Select'} , { class: "form-control" }) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :hiring, class: "control-label col-sm-4" %>
      <div class="col-sm-2">
        <%= f.check_box :hiring %>
      </div>
      <%= f.label :fund_raising, class: "control-label col-sm-4" %>
      <div class="col-sm-2">
        <%= f.check_box :fund_raising %>
      </div>
    </div>
    <%= render 'company_location', f: f %>
    <%= render 'company_phone', f: f %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-4 col-sm-5">
    <%= f.submit 'Save', class: "btn btn-success" %>
    <%= link_to 'Back', admin_companies_path, class: "btn btn-default" %>
  </div>
</div>

app/views/admin/companies/edit.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading">Edit Company
        </div>
        <div class="panel-body">
          <%= form_for @company, url: {action: "update"}, html:{ class: "admin-company form-horizontal" } do |f| %>
          <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/companies/index.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12" style="width: 104%;">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading" style="height: 48px">Companies List
          <p class="pull-right"><%= link_to 'Add Company', new_admin_company_path, class: "btn btn-primary btn-sm" %></p></div>
          <div class="panel-body">
            <table class="table table-bordered table-striped table-hover" id="companies_list">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Employees count</th>
                  <th>Established date</th>
                  <th>Website</th>
                  <th>Email</th>
                  <th>Revenue</th>
                  <th>Company Type</th>
                  <th style='width: 9%;'>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @companies.each do |company| %>
                <tr>
                  <td><%= company.name %></td>
                  <td><%= company.employees_count %></td>
                  <td><%= company.established_date %></td>
                  <td style="width: 280px;" class="wordbreak"><%= company.website %></td>
                  <td><%= company.email %></td>
                  <td><%= company.revenue %></td>
                  <td><%= company.company_type.name if company.company_type %></td>
                  <td><%= link_to '', '/admin/companies/' + company.id.to_s, class: "btn btn-xs btn-info fa fa-eye", title: "View" %>
                    <%= link_to '', edit_admin_company_path(company), class: "btn btn-xs btn-warning fa fa-edit", title: "Edit" %>
                    <%= link_to '', '/admin/companies/' + company.id.to_s, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger fa fa-trash-o", title: "Delete" %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <div class="pull-right"><%= paginate @companies %></div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/admin/companies/new.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading">New Company
        </div>
        <div class="panel-body">
          <%= form_for @company, url: {action: "create"}, html:{ class: "admin-company form-horizontal" } do |f| %>
          <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/companies/show.html.erb
<div class="blog blog-category blog-archive container">
  <div class="blog-category">
    <div class="row col-lg-12">
      <h1></h1>
      <div class="panel panel-default">
        <div class="panel-heading">Company Information
        </div>
        <div class="panel-body">
          <form class="form-horizontal" role="form">
          <div class="col-md-12">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label col-sm-4">Company Name:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.name %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Sector:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.sectors.first.name if @company.sectors.first %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Employees Count:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.employees_count %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Established Date:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.established_date %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Summary:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.summary %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Website:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.website %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Email:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.email %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Revenue:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.revenue %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Company Type:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.company_type.name %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Hiring:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.hiring ? "Yes" : "" %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Fund raising:</label>
              <div class="col-sm-8 form-control-static">
                <%= @company.fund_raising ? "Yes" : "" %>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <% @company.locations.each do |location| %>
            <div class="form-group">
              <label class="control-label col-sm-4">Street:</label>
              <div class="col-sm-8 form-control-static">
                <%= location.street %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">City:</label>
              <div class="col-sm-8 form-control-static">
                <%= location.city %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">State:</label>
              <div class="col-sm-8 form-control-static">
                <%= location.state %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Country:</label>
              <div class="col-sm-8 form-control-static">
                <%= location.country %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Pin Code:</label>
              <div class="col-sm-8 form-control-static">
                <%= location.pin_code %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Headquarter</label>
              <div class="col-sm-8 form-control-static">
                <%= location.is_headquarter ? "Yes" : "No" %>
              </div>
            </div>

            <% end %>

            <% @company.phones.each do |phone| %>
            <div class="form-group">
              <label class="control-label col-sm-4">Mobile:</label>
              <div class="col-sm-8 form-control-static">
                <%= phone.mobile %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">Phone:</label>
              <div class="col-sm-8 form-control-static">
                <%= phone.landline %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4">FAX:</label>
              <div class="col-sm-8 form-control-static">
                <%= phone.fax %>
              </div>
            </div>
            <% end %>
            </div></div>

            <div class="form-group">
              <div class="col-sm-offset-4 col-sm-5">
                <%= link_to 'Edit', edit_admin_company_path(@company), class: "btn btn-warning" %>
                <%= link_to 'Back', admin_companies_path, class: "btn btn-default" %>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>